name: Increment Version Number

on:
  pull_request:
    types:
      - opened

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract current version number
      id: get_version
      run: |
        CURRENT_VERSION=$(grep -m 1 '^## Version:' CanOpener.toc | sed 's/## Version: //')
        echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
        echo "Current version is $CURRENT_VERSION"

    - name: Increment version number
      id: increment_version
      run: |
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
        PATCH_VERSION=${VERSION_PARTS[2]}
        NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH_VERSION"
        sed -i "s/^## Version: .*/## Version: $NEW_VERSION/" CanOpener.toc
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "Version incremented to $NEW_VERSION"

    - name: Push changes to PR branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin ${{ github.head_ref }}
        git checkout ${{ github.head_ref }}
        git add CanOpener.toc
        git commit -m "Increment version to ${{ env.NEW_VERSION }} for PR #${{ github.event.pull_request.number }}"
        git push origin ${{ github.head_ref }}
